### ISSUE TITLE
Better "subserializer" support

### ISSUE THREAD

**Issue by ans-ioki** [ioki-mobility/lightweight_serializer#10]
When nested serializers are defined with `{ ModelClass => SerializerClass, .... }` the code doing the lookup uses

```
def serializer_for(serializer_data, model_class)
      if serializer_data.is_a?(Hash)
        serializer_data[model_class]        <---- returns a nil if it can't match on the class.
      else
        serializer_data
      end
    end
```

if serializer_data[model_class] misses to match nil is returned. subsequent code will call new on the "not found" serializer. It happened quite often during the last weeks that we had annoying debug sessions where a good error message could save lots of time. Sth like "Could not resolve (nested) serializer. Object to be serialized is of class XYZ, only serializers for [A, B, C] are defined....". Something like this.

Another feature could also be to support "inheritance". If no perfectly fitting serializer is found (say i serialize a nested student but only have serializers for persons and cars) maybe a parent class serializer is available (serialize student with person serializer).

So the topics would be:
- [ ] Better error messages when serializer resolving fails
- [ ] Optional: Match instances to serializers for parent class objects

**Comment by klaustopher** [comment]
Yeah, I think it makes sense, that this lookup will raise an error, when we don't find the appropriate class.

For the other solution, lookup based on inheritance might be harder to implement as this would require to loop through the entire keyspace of the hash and that would eliminate the O(1) lookup cost inside the hash.

WDYT about an alternative, that we can specify a fallback:

```ruby
collection :drinks, serializer: {
  Drink          => DrinkSerializer,
  HeatedDrink    => HeatedDrinkSerializer,
  UnbrandedDrink => UnbrandedDrinkSerializer,
  fallback: GenericDrinkSerializer
}
```

This way we could implement it as:

```ruby
serializer_data.fetch(model_class) do |key|
  serializer_data[:fallback] or raise(ArgumentError, "There's no serializer defined for a model of type #{key}")
end
```

WDYT?
